# Generated by Django 3.2.3 on 2021-09-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Pass', models.CharField(default='', max_length=50)),
                ('ConfrimPass', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=50, null=True)),
                ('LastName', models.CharField(default='', max_length=50, null=True)),
                ('Age', models.CharField(default='', max_length=10, null=True)),
                ('PhoneNumber', models.CharField(default='', max_length=50, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ProfilePic', models.ImageField(null=True, upload_to='profile/')),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.registerationmodel')),
            ],
        ),
    ]
