# Generated by Django 3.2.3 on 2021-09-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='user_email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.registerationmodel'),
        ),
    ]
