# Generated by Django 3.2.3 on 2021-10-13 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Register_Login.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f9d2474-b635-422a-92b0-353fbd9717bd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='percentage',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='totalOrderItemPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
