# Generated by Django 3.1.7 on 2022-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_accesstoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ProfilePic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
