# Generated by Django 3.2.3 on 2021-10-03 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_auto_20211003_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orders',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1822f4bd-a3d3-496e-9ef5-6b746a5ee204'), editable=False, primary_key=True, serialize=False),
        ),
    ]
