# Generated by Django 3.2.3 on 2021-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_alter_userinformationmodel_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='Age',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registerationmodel',
            name='FirstName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registerationmodel',
            name='LastName',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registerationmodel',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registerationmodel',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='registerationmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='ConfrimPass',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='Pass',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserInformationModel',
        ),
    ]
