# Generated by Django 3.2.3 on 2021-11-13 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_auto_20211013_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a71ffdaa-e7b1-4b5e-aaae-08e03d07873f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
