# Generated by Django 3.2.3 on 2021-12-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_alter_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='order',
        ),
    ]
