# Generated by Django 3.2.3 on 2021-11-13 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_auto_20211113_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='oldPrice',
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('657bc22d-ece0-482a-bf4b-3999633b9cc0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
