# Generated by Django 3.2.3 on 2021-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_auto_20210920_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationmodel',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registerationmodel',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
