# Generated by Django 3.2.3 on 2021-10-04 13:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_auto_20211003_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Register_Login.OrderItem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('188014cc-3d26-4a10-957c-cc1637fac555'), editable=False, primary_key=True, serialize=False),
        ),
    ]
