# Generated by Django 3.2.3 on 2021-12-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0004_remove_cartitems_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
