# Generated by Django 3.2.3 on 2021-11-13 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0004_auto_20211113_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5c04515-0bf2-4ec1-bb8a-8b6812060de6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
