# Generated by Django 3.2.3 on 2021-11-13 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0005_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('249cf58e-204c-4847-9834-53b39d2e6a2b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
