# Generated by Django 3.2.3 on 2021-11-13 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0006_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05a6a4f1-6763-4a6a-b8d4-1ded2c407576'), editable=False, primary_key=True, serialize=False),
        ),
    ]
