# Generated by Django 3.2.3 on 2021-09-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0007_alter_registerationmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationmodel',
            name='Email',
        ),
    ]
