# Generated by Django 3.2.3 on 2021-11-13 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0007_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dca022c7-36ba-4b37-9bbf-33ddd393d6b9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
