# Generated by Django 3.2.3 on 2021-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0008_remove_registerationmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationmodel',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
