# Generated by Django 3.2.3 on 2021-11-13 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0008_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c96c841c-f12a-4b13-a5ed-a226c51eb093'), editable=False, primary_key=True, serialize=False),
        ),
    ]
