# Generated by Django 3.2.3 on 2021-11-13 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_alter_bromocode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='NewProducts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='TopSelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7641251-3040-468e-a9f3-b118941e8909'), editable=False, primary_key=True, serialize=False),
        ),
    ]
