# Generated by Django 3.2.3 on 2021-11-13 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0010_auto_20211113_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af71d9e6-6eb6-4ae0-8288-269f77c0afd6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
