# Generated by Django 3.2.3 on 2021-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0010_remove_registerationmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
