# Generated by Django 3.2.3 on 2021-11-13 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0011_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5f1d176-0c2a-4ec0-b1af-c25e2d9248ba'), editable=False, primary_key=True, serialize=False),
        ),
    ]
