# Generated by Django 3.2.3 on 2021-11-13 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0012_alter_bromocode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b61bb463-4aec-43f3-b558-c4db84104265'), editable=False, primary_key=True, serialize=False),
        ),
    ]
