# Generated by Django 3.2.3 on 2021-09-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0012_alter_registerationmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationmodel',
            name='username',
        ),
    ]
