# Generated by Django 3.2.3 on 2021-09-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register_Login', '0013_remove_registerationmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='username',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='auth.user', to_field='username'),
            preserve_default=False,
        ),
    ]
