# Generated by Django 3.2.3 on 2021-11-13 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0013_auto_20211113_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('907e091c-3116-42cd-b066-5b3d8efe225c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
