# Generated by Django 3.2.3 on 2021-11-13 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0014_alter_bromocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bromocode',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3ca95e3-b8c7-4925-9190-c863a3fd2663'), editable=False, primary_key=True, serialize=False),
        ),
    ]
