# Generated by Django 3.2.3 on 2021-09-21 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register_Login', '0019_remove_registerationmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='username',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
