# Generated by Django 3.2.3 on 2021-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0022_alter_registerationmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationmodel',
            name='Email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
