# Generated by Django 3.2.3 on 2021-09-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0023_registerationmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerationmodel',
            name='Email',
        ),
    ]
