# Generated by Django 3.2.3 on 2021-09-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0028_bromocode_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
    ]
