# Generated by Django 3.2.3 on 2021-09-24 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Register_Login', '0029_alter_order_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterationModel',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='bromocode',
            options={'verbose_name_plural': 'BromoCodes'},
        ),
    ]
