# Generated by Django 3.2.3 on 2022-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_auto_20220305_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
