# Generated by Django 3.2.3 on 2022-03-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0003_auto_20220311_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offerPercentage',
        ),
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
