# Generated by Django 3.2.3 on 2022-03-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0004_auto_20220312_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('brand', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('oldPrice', models.FloatField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('TopSelling', models.BooleanField(default=False)),
                ('NewProducts', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
