# Generated by Django 3.2.3 on 2022-03-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0005_auto_20220312_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsales',
            options={'verbose_name_plural': 'Products Sales'},
        ),
    ]
