# Generated by Django 3.1.7 on 2022-02-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0002_auto_20220211_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='email',
            new_name='user',
        ),
    ]
