# Generated by Django 3.2.3 on 2022-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0004_auto_20220305_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
